apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quotes-demo-app.fullname" . }}-config
  labels:
    {{- include "quotes-demo-app.labels" . | nindent 4 }}
data:
  application.properties: |
    server.port={{ .Values.app.port }}
    spring.application.name={{ .Values.app.name }}
    greeting.message=Hello from Spring Boot!