apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quotes-demo-app.fullname" . }}
  labels:
    {{- include "quotes-demo-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "quotes-demo-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "quotes-demo-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
          env:
            - name: SPRING_APPLICATION_NAME
              value: "{{ .Values.app.name }}"
            - name: SERVER_PORT
              value: "{{ .Values.app.port }}"
          livenessProbe:
            path: /actuator/health/liveness
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            path: /actuator/health/readiness
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}